{
 "title": "SonarQube",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "branchName",
    "label": "Branch Name",
    "query": "label_values(sonarqube_bugs, branch)"
   },
   {
    "name": "projectName",
    "label": "Project Name",
    "query": "label_values({branch=\"$branchName\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "projectName" },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 26 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 31 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 36 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 41 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 41 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 41 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 41 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 46 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 46 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 46 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 46 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 51 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 51 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 51 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 51 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 56 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 56 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 56 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 56 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 56 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 61 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 61 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 61 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 61 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 61 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 66 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 66 },
   "repeat": "branchName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 66 },
   "repeat": "branchName",
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 66 },
   "repeat": "branchName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\", branch=\"$branchName\"}"
    }
   ]
  }
 ]
}